/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AgencyService } from "../agency.service";
import { AgencyCreateInput } from "./AgencyCreateInput";
import { Agency } from "./Agency";
import { AgencyFindManyArgs } from "./AgencyFindManyArgs";
import { AgencyWhereUniqueInput } from "./AgencyWhereUniqueInput";
import { AgencyUpdateInput } from "./AgencyUpdateInput";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";

export class AgencyControllerBase {
  constructor(protected readonly service: AgencyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Agency })
  async createAgency(@common.Body() data: AgencyCreateInput): Promise<Agency> {
    return await this.service.createAgency({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        name: true,
        numberField: true,
        drivers: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Agency] })
  @ApiNestedQuery(AgencyFindManyArgs)
  async agencies(@common.Req() request: Request): Promise<Agency[]> {
    const args = plainToClass(AgencyFindManyArgs, request.query);
    return this.service.agencies({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        name: true,
        numberField: true,
        drivers: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Agency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async agency(
    @common.Param() params: AgencyWhereUniqueInput
  ): Promise<Agency | null> {
    const result = await this.service.agency({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        name: true,
        numberField: true,
        drivers: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Agency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAgency(
    @common.Param() params: AgencyWhereUniqueInput,
    @common.Body() data: AgencyUpdateInput
  ): Promise<Agency | null> {
    try {
      return await this.service.updateAgency({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          name: true,
          numberField: true,
          drivers: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Agency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAgency(
    @common.Param() params: AgencyWhereUniqueInput
  ): Promise<Agency | null> {
    try {
      return await this.service.deleteAgency({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          name: true,
          numberField: true,
          drivers: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/orders")
  @ApiNestedQuery(OrderFindManyArgs)
  async findOrders(
    @common.Req() request: Request,
    @common.Param() params: AgencyWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findOrders(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        time: true,
        active: true,
        uid: true,
        driver: true,
        ride: true,

        agency: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orders")
  async connectOrders(
    @common.Param() params: AgencyWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        connect: body,
      },
    };
    await this.service.updateAgency({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orders")
  async updateOrders(
    @common.Param() params: AgencyWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        set: body,
      },
    };
    await this.service.updateAgency({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orders")
  async disconnectOrders(
    @common.Param() params: AgencyWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        disconnect: body,
      },
    };
    await this.service.updateAgency({
      where: params,
      data,
      select: { id: true },
    });
  }
}
